name: Generate Datas

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate snake svg
        uses: Platane/snk@master
        with:
          github_user_name: kayamii
          svg_out_path: dist/github-contribution-grid-snake.svg
